# Generated by Django 4.1.3 on 2022-11-16 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtime',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='classtime',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 11, 0)),
        ),
    ]
