# Generated by Django 4.1.3 on 2022-11-16 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_subscription_alter_user_phone_number_and_more'),
        ('studios', '0002_alter_studioamenities_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.classtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
