# Generated by Django 4.1.3 on 2022-11-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_classbooking'),
        ('studios', '0003_classbooking 2'),
    ]

    operations = [
    ]
