# Generated by Django 4.1.3 on 2022-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_rename_start_time_classtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
    ]
