# Generated by Django 4.1.3 on 2022-11-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_merge_0003_classbooking_0003_classbooking 2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'Coaches'},
        ),
    ]
