# Generated by Django 4.1.3 on 2022-11-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
