# Generated by Django 4.1.3 on 2022-11-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='length',
            new_name='length_months',
        ),
    ]
