# Generated by Django 4.1.3 on 2022-12-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_length_months'),
        ('subscriptions', '0003_alter_subscription_length_months 2'),
    ]

    operations = [
    ]
