# Generated by Django 4.1.3 on 2022-11-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_rename_time_classtime_start_time_classtime_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
