# Generated by Django 4.1.3 on 2022-12-04 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studios', '0005_alter_classtime_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBookingArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.classtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
