# Generated by Django 4.1.3 on 2022-12-08 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_length_subscription_length_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='length_months',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
