# Generated by Django 4.1.3 on 2022-11-17 18:39

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_paymentinfo_expiry_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='next_billing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='expiry',
            field=creditcards.models.CardExpiryField(blank=True, null=True, verbose_name='expiration date'),
        ),
    ]
