# Generated by Django 4.1.3 on 2022-12-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_user_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
