# Generated by Django 4.1.3 on 2022-11-16 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '__first__'),
        ('User', '0002_user_subscription_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_on', models.DateTimeField(auto_now=True)),
                ('payment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.paymentinfo')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
