# Generated by Django 4.1.3 on 2022-11-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_path',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
