# Generated by Django 4.1.3 on 2022-11-16 04:43

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_avatar_path_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_number',
            field=creditcards.models.CardNumberField(max_length=25, verbose_name='card number'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='cvv',
            field=creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='expiration_date',
            field=creditcards.models.CardExpiryField(verbose_name='expiration date'),
        ),
    ]
