# Generated by Django 4.1.3 on 2022-11-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_next_billing_date_alter_paymentinfo_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
