# Generated by Django 4.1.3 on 2022-11-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_last_login_alter_user_avatar_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
