# Generated by Django 4.1.3 on 2022-11-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payment_info', to='User.paymentinfo'),
        ),
    ]
