# Generated by Django 4.1.3 on 2022-11-16 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_paymentinfo_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='expiration_date',
            new_name='expiry',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('payment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.paymentinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
