# Generated by Django 4.1.3 on 2022-11-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_paymentinfo_expiry_delete_admin'),
        ('User', '0004_delete_admin'),
    ]

    operations = [
    ]
