# Generated by Django 4.1.3 on 2022-11-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
